version: "3.7"
services:
  # The Penumbra daemon
  pd:
    container_name: penumbra
    build:
      context: .
    environment:
      - RUST_LOG=${RUST_LOG:-warn,pd=info,penumbra=info}
    command: pd start --host 0.0.0.0 --database-uri
      postgres://postgres:postgres@db/penumbra
    restart: on-failure
    # depends_on:
    #   - tendermint-node0
    networks:
      localnet:
        ipv4_address: 192.167.10.6
    ports:
      - "26658:26658"
      - "26666:26666"
      - "26667:26667"

  # The Tendermint node
  tendermint-node0:
    image: "tendermint/tendermint:v0.35.0"
    container_name: tendermint-node0
    ports:
      - "26656:26656"
      - "26657:26657"
    volumes:
      - ~/scratch/testnet_build/node0:/tendermint
    command: start --proxy-app=tcp://pd:26658
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    depends_on:
      - pd
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  # The Tendermint node
  # tendermint-node1:
  #   image: "tendermint/tendermint:latest"
  #   container_name: tendermint-node1
  #   ports:
  #     - "26659-26660:26656-26657"
  #   volumes:
  #     - ~/scratch/testnet_build/node1:/tendermint:Z
  #   command: start --proxy-app=tcp://pd:26658
  #   environment:
  #     - ID=1
  #     - LOG=${LOG:-tendermint.log}
  #   depends_on:
  #     - pd
  #   networks:
  #     localnet:
  #       ipv4_address: 192.167.10.3

  # # The Tendermint node
  # tendermint-node2:
  #   image: "tendermint/tendermint:latest"
  #   container_name: tendermint-node2
  #   ports:
  #     - "26661-26662:26656-26657"
  #   volumes:
  #     - ~/scratch/testnet_build/node2:/tendermint:Z
  #   command: start --proxy-app=tcp://pd:26658
  #   environment:
  #     - ID=2
  #     - LOG=${LOG:-tendermint.log}
  #   depends_on:
  #     - pd
  #   networks:
  #     localnet:
  #       ipv4_address: 192.167.10.4

  # # The Tendermint node
  # tendermint-node3:
  #   image: "tendermint/tendermint:latest"
  #   container_name: tendermint-node3
  #   ports:
  #     - "26663-26664:26656-26657"
  #   volumes:
  #     - ~/scratch/testnet_build/node3:/tendermint:Z
  #   command: start --proxy-app=tcp://pd:26658
  #   environment:
  #     - ID=3
  #     - LOG=${LOG:-tendermint.log}
  #   depends_on:
  #     - pd
  #   networks:
  #     localnet:
  #       ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
