name: Smoke Test
on: [push]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build the testnet.
        run: |
          ./scripts/docker_compose_freshstart.sh
          chmod -R 777 ~/.penumbra/testnet_data
          docker-compose build

      - name: Run testnet for smoke test duration.
        run: timeout --preserve-status $TESTNET_RUNTIME docker-compose up --exit-code-from pd-node0
        env:
          TESTNET_RUNTIME: 4m
